services:
  web-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: TomcatWS
    ports:
      - "8888:8080"
    develop:
      watch:
        - action: rebuild
          path: target/funciona-latest/
          target: /usr/local/tomcat/webapps/funciona
  db:
    image: mysql:8.0.38
    container_name: MySQL-Database
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD="Cibertec2024"
    depends_on:
      - web-server
volumes:
  mysql-data:
